name: compile jars

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Build all the jars
        run: |
          mvn install -P linux-amd64
          mvn install -P macos-amd64
          mvn install -P windows-amd64
      - name: Commit jar to build branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp editor/target/editor-*-*.jar ./
          cp server/target/server-*.jar ./
          git add -f ./*.jar
          git commit -m "Update Jars by workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "build"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
